### PR TITLE
feat(breakpoint-vars): add vars for breakpoints to use in JS

### PR DESCRIPTION
**Pull request by zak-eddingtonPOP**
Create a consistent way for components to check the current breakpoint for conditional logic and/or rendering. This will help prevent hardcoding breakpoints in components and reinventing ways to determine the current breakpoint.

Features added:
- --kd-current-breakpoint variable that sets the breakpoint name
- enum def of all breakpoint values
- helper method to get this value from the CSS variable
- export helpers and defs so they can be referenced in content/application (duplicate helpers should be removed from those repos)

Usage:
Components can add a resize event to call the helper method to get the CSS value and match it to the correct enum value to determine the current breakpoint.

### CODE REVIEW

**Review by brian-patrick-3 — CHANGES_REQUESTED** [review]
My only concern is the helpers were intended to be internal, like the options array one is for storybook usage specifically. We should separate into different files if we want to expose any externally.

**Comment by zak-eddingtonPOP** [comment]
I agree on splitting them. It'll help for organization as well.

How about:

helpers/breakpoints.ts
- getCurrentBreakpoint

helpers/events.ts
- debounce

helpers/storybook.ts
- stringToReactHtml
- createOptionsArray

**Comment by zak-eddingtonPOP** [comment]
The current use case for breakpoints in JS is with swapping the icon size on mobile vs desktop, but this will be needed for much more significant logic later. 

For example, a component may collapse content into an accordion on mobile, but display it on desktop. Or a carousel will display 3 items at a time on desktop and only 1 on mobile. Things like that.

**Comment by brian-patrick-3** [comment]
I think those scenarios kinda go against our responsive design principles. Same content, all screen sizes. Ex: An accordion on desktop must also be an accordion on mobile. 

As far as conditional rendering goes, I'd argue for CSS media queries over JS logic. And the reason we only have SASS vars for the breakpoints is because CSS cars can't be used in media queries

**Comment by zak-eddingtonPOP** [comment]
OK, but that's not the reality we face. JS logic will have dependencies on the current breakpoint. The application header component is already an example of it. This is just providing a uniform way to determine the breakpoint so we are not reinventing it per component. It's also centralizing the definitions so they are not hardcoded everywhere.

**Comment by brian-patrick-3** [comment]
> OK, but that's not the reality we face. JS logic will have dependencies on the current breakpoint. The application header component is already an example of it. This is just providing a uniform way to determine the breakpoint so we are not reinventing it per component. It's also centralizing the definitions so they are not hardcoded everywhere.

The Header is a much different scenario. It needs a custom breakpoint because it depends on the overall width of the combined navigation links, and not the viewport size. I would love to find a better way to address that actually.

You might be putting the cart before the horse a bit here with the changes, especially in Foundation. Stuff like this really needs to be discussed at the design level with both Content and Application teams before any implementation.

**Comment by zak-eddingtonPOP** [comment]
Honestly, I'm not sure what the push back is with this. There will always be a need for JS to determine the breakpoint to optimize functionality across screen sizes or render different markup/components accordingly.

The foundation is the place to determine how this is done since this is where breakpoints are defined. The foundation is also the place to define this logic and helper methods that will be reused across platforms.

If there's a better way to define and determine the breakpoint for JS components, I'm all for it. But it's a necessary feature that needs to be included in the foundation.

**Comment by zak-eddingtonPOP** [comment]
I've split the helpers out into individual files for better organization.

I did not add any storybook documentation pages for these as they are all still intended for internal use within the library itself and not meant to be used by consumers of the design system. Comments within the helper files provides the documentation for developers.

However, they still need to be exported so the content/application repos can import and use them instead of duplicating them within each repo.

**Review by brian-patrick-3 — APPROVED** [review]

**Pull request merged**
