### PR TITLE
fix: link icon position fix

### PR DESCRIPTION
**Pull request by tulasigudibanda**
## ADO Story or GitHub Issue Link

https://github.com/kyndryl-design-system/shidoka-foundation/issues/73

### CODE REVIEW

**Review by brian-patrick-3 — APPROVED** [review]

**Comment by tulasigudibanda** [comment]
@srpriyankashetty  , build:test error seems to be related to playwright and ubuntu 24.04. It's not failing in other repos though, so maybe an npm cache issue. Checked with Brian. So you can please go ahead and test.

**Review by srpriyankashetty — APPROVED** [review]
Verified and looks fine
image

**Pull request merged**
