### PR TITLE
test: overhauled testing suite

### PR DESCRIPTION
**Pull request by brian-patrick-3**
See [this Teams thread](https://teams.microsoft.com/l/message/19:QAPcSfiF3uWT07ljsS0_sVcRA1TFY-xNIHRqADOwaeo1@thread.tacv2/1711646121354?tenantId=f260df36-bc43-424c-8f44-c85226657b01&groupId=ae775dbb-d5f4-4f3a-aa62-8cfc1765b347&parentMessageId=1711646121354&teamName=Shidoka%20(Private)&channelName=General&createdTime=1711646121354) for the full details.

### CODE REVIEW

**Review by maulik-thaker1 — APPROVED** [review]
Overall looks good. Curious about how to run interaction testing in storybook. Right now I can see only link has 3 interactions. 

Also, are we only need to deal with storybook add-ons for various testing or we are open to import testing tools ?

Any learning curve to write interaction testing or any type of testing ?  

Why we removed unit testing ? - Are we planning to add later ?

**Comment by brian-patrick-3** [comment]
> Overall looks good. Curious about how to run interaction testing in storybook. Right now I can see only link has 3 interactions.
> 
> Also, are we only need to deal with storybook add-ons for various testing or we are open to import testing tools ?
> 
> Any learning curve to write interaction testing or any type of testing ?
> 
> Why we removed unit testing ? - Are we planning to add later ?

1. Yeah I only wrote one sample interaction test for the link component. It simulates a click and check the on-click event gets fired. Interaction tests run automatically when you view the story, and you can rewind and step through them.
2. Yeah Storybook covers everything for us except for unit tests.
3. Tests are written with [Testing Library](https://testing-library.com/), and I've included [shadow-dom-testing-library](https://www.npmjs.com/package/shadow-dom-testing-library) to allow us to piece the shadow DOM. There will probably be some learning required, and we need to decide what types of interaction tests would be worth writing.
4. As I mentioned in teams, our old unit tests were made redundant by all of these new tests, particularly snapshot tests.

**Comment by maulik-thaker1** [comment]
> > 4> I think it's better to write UT's as it's giving you the code coverage of your component but we need to add this only once component is freezzed i.e. no more modification ahead otherwise keep changing unit testing is also a headache.
> 
> The only UTs we had before we basically checking that the component mounted, and maybe a few that compared HTML. We get all of that automatically just with Snapshot tests. Are there specific unit tests you think would be valuable in addition? We can now write Interaction tests, which are basically unit tests. And we also get Accessibility tests, and Visual testing if we keep Chromatic. I guess I'm just not seeing what unit tests can offer over those.

yeah agreed.

**Comment by brian-patrick-3** [comment]
@maulik-thaker1 Did you receive an email from Chromatic for the UI Review on this PR? I sent it to all designers/devs as a preview. Curious what you think of it.

**Comment by maulik-thaker1** [comment]
> @maulik-thaker1 Did you receive an email from Chromatic for the UI Review on this PR? I sent it to all designers/devs as a preview. Curious what you think of it.

not yet I checked my mails

**Comment by brian-patrick-3** [comment]
@kyndryl-design-system/ui-devs  I'm having second thoughts about even bothering with Snapshot (HTML) tests after reading this article: https://medium.com/@sapegin/whats-wrong-with-snapshot-tests-37fbe20dfe8e

Seems like they don't really add any value, and will just be something we annoyingly update after every change. Visual tests will also make HTML Snapshots redundant. I'm thinking we just go with Accessibility, Interaction (strategy TBD), and Visual. What do you think?

**Pull request merged**
