### PR TITLE
feat(card): skeleton

### PR DESCRIPTION
**Pull request by kumarivijeta**
## Summary

Card skeleton token update

## ADO Story 

[TASK 2003585](https://dev.azure.com/Kyndryl/Shidoka%20-%20Bridge%20Design%20System/_workitems/edit/2003585)

## Figma Link

https://www.figma.com/design/CQuDZEeLiuGiALvCWjAKlu/branch/qMpff4GuFUEcsMUkvacS3U/Applications---Component-Library?node-id=19896-36062&m=dev

## Checklist

- [x] Used Conventional Commit messages as outlined in the contributing guide.
  - [ ] Noted breaking changes (if any).
- [ ] Documented/updated all props, events, slots, parts, etc with JSDoc.
  - [x] Ran the `analyze` command to update Storybook docs.
- [ ] Added/updated Stories with controls to cover all variants.
- [ ] Ran `test` locally to address any failures.
- [ ] Added/updated the Figma link for the Story's Design tab.

### CODE REVIEW

**Comment by kumarivijeta** [comment]
> Hi @kumarivijeta , I see cards with buttons as visit link and tags in Figma, we don't have any sample component in story book? Are those configurable by dev end?

> Hi @srpriyankashetty Those are part of informational and vital card story which is in applications.

**Review by brian-patrick-3 — APPROVED** [review]

**Comment by srpriyankashetty** [comment]
As per discussion with @kumarivijeta , the waiting for the boarder token in the dark mode for Card
image

**Comment by srpriyankashetty** [comment]
Hi @kumarivijeta , 
1. The blank card when made clickable, the hide boarder is not hiding the boarder
2. The Inside grid cards, changes made in the Controls (like type and target) are not reflecting - is this, okay?

**Comment by kumarivijeta** [comment]
> Hi @kumarivijeta ,
> 
> 1. The blank card when made clickable, the hide boarder is not hiding the boarder
> 2. The Inside grid cards, changes made in the Controls (like type and target) are not reflecting - is this, okay?

> Hi @srpriyankashetty 
>1. Arguments were not passed for hide border in blank card which causes the issue. - Resolved.
>2. The grids Cards inherits the cards control's and it is just a pattern. IMO it is fine for now.

**Review by srpriyankashetty — APPROVED** [review]
Verified and looks fine

**Pull request merged**
